### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by stecydube** [noatpad/obsidian-banners#51]
Uncaught (in promise) TypeError: Cannot destructure property 'src' of 'this.metaManager.getBannerDataFromFile(...)' as it is null.
    at Mu.lintBannerSource (eval at <anonymous> (app.js:1:1490278), <anonymous>:28:11207)
    at eval (eval at <anonymous> (app.js:1:1490278), <anonymous>:28:9262)
    at Array.forEach (<anonymous>)
    at Mu.loadPrecheck (eval at <anonymous> (app.js:1:1490278), <anonymous>:28:9246)
    at Mu.onload (eval at <anonymous> (app.js:1:1490278), <anonymous>:28:7162)

Version 1.3.2
Obsidian 0.14.5
Windows 10

**Comment by noatpad** [comment]
Ay, must've missed that case. Should be an easy fix and I can release a hotfix in a tad. Release should be out once I close this shortly

**Comment by stecydube** [comment]
Confirmed fixed. Thank you.
