### ISSUE TITLE
Error creating View

### ISSUE THREAD

**Issue by pinknicolekaro** [noatpad/obsidian-banners#94]
Hello,
I installed banners plugin right now and setup a banner for a page. I can see it in edit mode but in Preview mode there is just blank space where the banner should be.
I looked in Dev Console and found this

``` sh
plugin:obsidian-banners:22 Uncaught TypeError: u.startsWith is not a function
    at LM (plugin:obsidian-banners:22:1410)
    at OM (plugin:obsidian-banners:28:971)
    at Ge.onload (plugin:obsidian-banners:28:1402)
    at Ge.e.load (app.js:1:864580)
    at t.e.addChild (app.js:1:864981)
    at Object.addChild (app.js:1:1295113)
    at eval (plugin:obsidian-banners:28:3134)
    at Function.t.postProcess (app.js:1:1296170)
    at t.postProcess (app.js:1:1294998)
    at h (app.js:1:1006344)
```

Can you please check?
If you need more Information regarding my other used plugins feel free to ask

**Comment by mariomui** [comment]
@pinknicolekaro the new banners doesn't accept arrays. You'l have to wrap the banner value with quotes "http://...jpeg"
